### ISSUE TITLE
In version 0.2 <Barcode> views have a width and height of 0x0

### ISSUE THREAD

**Issue by aardvarkk** [TheBlindHawk/react-native-barcoder#7]
I can't make a <Barcode> element lay out properly because the container views have dimension 0x0, likely due to the absolute positioning used by the <Section> element. The element appears to occupy a 0x0 space, and is thus drawn over/under surrounding elements.

Compare the following:

Version 0.2.0:

![image](https://github.com/TheBlindHawk/react-native-barcoder/assets/1251092/34b11d22-99dd-466b-9b0f-866a72f66c9a)

Notice no width or height are shown.

Version 0.1.1:

![image](https://github.com/TheBlindHawk/react-native-barcoder/assets/1251092/3362f390-2697-4305-813f-6a70eeaa72ff)

**Comment by aardvarkk** [comment]
This issue, in combination with #6 has required me to downgrade back to 0.1.1

**Comment by TheBlindHawk** [comment]
Hello @aardvarkk , thanks for opening the issue!

This issue should have been fixed with version 0.2.1 (which was not usable due to #6 ).
Could you test out version 0.2.2 and see if it works?

**Comment by TheBlindHawk** [comment]
I'll be closing this issue as it should be fixed in the latest version, feel free to open it again if it is persisting in future versions.

**Comment by TheBlindHawk** [comment]
I have uploaded a new version 0.2.4!
Most of the bugs related to the EAN adaptations in 0.2.X should be fixed there.
Estimating width and height should also work in the newer version.

If there are any other issues with the width and height of the element please let me know!

**Comment by TheBlindHawk** [comment]
I will be closing this issue for now.
Please feel free to reopen it or write another issue if a similar bug comes out!
